/*
 * dtalk_shim.h - C API for DoubleTalk PC Emulated Synthesizer Core
 *
 * Provides a clean C interface for initializing the 80C188EB / DoubleTalk PC emulator,
 * queuing ASCII control strings, rendering 16-bit PCM audio samples, and tracking index marks.
 */

#ifndef DTALK_SHIM_H
#define DTALK_SHIM_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dtalk_instance dtalk_t;

typedef struct {
    uint8_t value;
    uint64_t sample_pos;
} dtalk_index_mark_t;

/**
 * Creates a DoubleTalk PC emulator instance from firmware ROM bytes.
 * @param rom_data Pointer to the 512KB doubletalkpc.bin firmware binary data.
 * @param rom_size Size of the firmware binary (must be 524,288 bytes).
 * @return Opaque pointer to the initialized dtalk_t handle, or NULL on error.
 */
dtalk_t *dtalk_create(const uint8_t *rom_data, size_t rom_size);

/**
 * Destroys a DoubleTalk PC instance and frees associated resources.
 */
void dtalk_destroy(dtalk_t *dt);

/**
 * Resets the emulator CPU and speech synthesizer hardware state.
 */
void dtalk_reset(dtalk_t *dt);

/**
 * Returns the output PCM sample rate of the synthesizer in Hz (typically 10504 Hz).
 */
uint32_t dtalk_sample_rate(dtalk_t *dt);

/**
 * Queues ASCII text or DoubleTalk control commands (Ctrl-A / 0x01 prefixed) for speech synthesis.
 */
void dtalk_queue(dtalk_t *dt, const char *text, size_t len);

/**
 * Immediately halts synthesis and clears pending audio queues.
 */
void dtalk_stop(dtalk_t *dt);

/**
 * Configures the corner frequency (Hz) of the modeled reconstruction low-pass filter (2000 - 5000 Hz).
 */
void dtalk_set_lowpass_hz(dtalk_t *dt, uint32_t hz);

/**
 * Sets the rate boost level (0 = authentic 0-9 table, 1..3 = accelerated ROM table).
 */
void dtalk_set_rate_boost(dtalk_t *dt, int level);

/**
 * Returns the current rate boost level.
 */
int dtalk_get_rate_boost(dtalk_t *dt);

/**
 * Returns the maximum supported rate boost level.
 */
int dtalk_rate_boost_max(void);

/**
 * Returns 1 if speech synthesis is currently active, 0 otherwise.
 */
int dtalk_active(dtalk_t *dt);

/**
 * Renders up to max_samples signed 16-bit mono PCM frames into the provided buffer.
 * @return The actual number of samples rendered.
 */
size_t dtalk_synth16(dtalk_t *dt, int16_t *buf, size_t max_samples);

/**
 * Reads any passed index marks generated by '\x01<N>I' commands.
 * @return The number of index marks returned.
 */
size_t dtalk_read_index_marks(dtalk_t *dt, dtalk_index_mark_t *marks, size_t max_marks);

#ifdef __cplusplus
}
#endif

#endif /* DTALK_SHIM_H */
